config/routes.rb
Rails.application.routes.draw do
  resources :locations

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'locations#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
    validates :address, presence: true
    validates :city, presence: true
    geocoded_by :my_location
    after_validation :geocode
    

    def my_location
        "#{address}, #{city}, GA"
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  include LocationsHelper

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @buses = HTTParty.get('http://developer.itsmarta.com/BRDRestService/RestBusRealTimeService/GetAllBus')

    @bus_count = 0
    @nearby_bus = []
    if valid_location(@location)
    @buses.each do |bus|
      if nearby(@location.longitude,@location.latitude,bus["LONGITUDE"].to_f, bus["LATITUDE"].to_f)
        @bus_count += 1
        @nearby_bus.push(bus)

      end
    end
  else
    redirect_to new_location_path, notice: "Please enter a correct location"
  end

  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def location_params
      params.require(:location).permit(:address, :city, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def fetch_url_data(source)
        http = Net::HTTP.get_response(URI.parse(source))
        data = http.body
        response = JSON.parse(data)
        return response
      end
    
      def nearby(lng1, lat1, lng2, lat2)
        if (lng1 - lng2).abs <= 0.01 && (lat1 - lat2).abs <= 0.01
          return true
        else
          return false
        end
      end
end

app/helpers/locations_helper.rb
module LocationsHelper

    def valid_location(location)
        if location.latitude == nil || location.longitude == nil
            return false
        else
            return true
        end
    end


    def nearby(lng1,lat1,lng2,lat2)
        if (lng1-lng2).abs <= 0.01 && (lat1-lat2).abs <= 0.01
            return true
        else
            return false
        end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Marta</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=#{Figaro.env.google_map_api_key}' %>
</head>

<body>

<div class="container">
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<%= Figaro.env.google_map_api_key%>"></script>
    
    <%= yield %>
</div>
</body>

</html>

app/views/locations/_form.html.erb
<div class="container">
<%= form_with(model: location, local: true) do |form| %>
<% if location.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

    <ul>
        <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
</div>

<div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
</div>

<div class="actions">
    <%= form.submit 'Search', :class => 'btn btn-pimary btn-primary btn-xs' %>
</div>
</div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="navbar-brand">Marta
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <% link_to Rails.application.class.parent_name, root_url, :class=> "navbar-brand" %>
  </div>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="nav navbar-nav">
      <li>
        <%= link_to "Locations", locations_url %>
      </li>
    </ul>
  </div>
</nav>
<p id="notice"><%= notice %></p>

<h1>Locations</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>City</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.address %></td>
        <td><%= location.city %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path, :class => 'btn btn-info btn-primary btn-xs'%>

app/views/locations/new.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="navbar-brand">Marta
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <% link_to Rails.application.class.parent_name, root_url, :class=> "navbar-brand" %>
  </div>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="nav navbar-nav">
      <li>
        <%= link_to "Locations", locations_url %>
      </li>
    </ul>
  </div>
</nav>
<div class="jumbotron">
<%= notice %>
<h1>Atlanta Bus Tracker</h1>
<div class="col-md-5">
<p>
    Please give us your address or approximate location so we can tell you if there is a bus nearby.
</p>
<%= render 'form', location: @location %>
<%= link_to 'Back', locations_path, :class => 'btn btn-warning btn-primary btn-xs' %>
</div>
<div class="col-md-4">
        <%= image_tag("logo.png", size:"532x484", :class =>"style_image") %>
</div>

app/views/locations/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="navbar-brand">Marta
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <% link_to Rails.application.class.parent_name, root_url, :class => "navbar-brand" %>
  </div>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="nav navbar-nav">
      <li>
        <%= link_to "Locations", locations_url %>
      </li>
    </ul>
  </div>
</nav>
<p id="notice"><%= notice %></p>

<h2>You are currently standing at...</h2>
<p>
    <%= @location.my_location%>
</p>
<h2>The closest bus is...</h2>
<% if @bus_count > 1 %>
<% @nearby_bus.each_with_index do |bus, index| %>
<p>
    <strong>Route:</strong><%= bus["ROUTE"]%> <br>
    <strong>Vehicle:</strong><%= bus["VEHICLE"]%><br>
    <strong>Next Stop:</strong><%= bus["TIMEPOINT"]%>
</p>

<script>
      var map;
      function initMap() {
        var myCoords= { lat: <%=@location.latitude %>, lng: <%= @location.longitude %>};
        var busCoords = { lat: <%=bus['LATITUDE']%>, lng: <%= bus['LONGITUDE'] %>};

        map = new google.maps.Map(document.getElementById('map-canvas<%=index %>'), {
          center: myCoords,
          zoom: 13
        });
        var markerBus = new google.maps.Marker({
            position: busCoords,
            map: map
          });


          var infowindow = new google.maps.InfoWindow({
              content: "Your bus is here"
            });  


          markerBus.addListener('click', function () {
                infowindow.open(map, markerBus);
              });  

      }

      google.maps.event.addDomListener(window,'load',initMap);
    </script>
      <div id="map-canvas<%=index%>" style="height:300px; width: 300px;"></div>
      <% end %>
    <% else %>
    <p> .. sorry there is no buss near you. Call an Uber </p>
    <% end %>
<%= link_to 'Edit', edit_location_path(@location), :class => 'btn btn-primary btn-primary btn-xs'  %> |
<%= link_to 'Back', locations_path, :class => 'btn btn-warning btn-primary btn-xs'  %>